baseURL: 'https://suppers-ai.github.io/solobase-site/'
languageCode: 'en-us'
title: 'Solobase - Modern Admin Dashboard'
theme: 'solobase-theme'

params:
  description: 'Open source backend in a single binary'
  author: 'Suppers Software Limited'
  logo: '/images/solobase-logo.svg'
  demo_url: 'https://solobase-demo.fly.dev/'
  github_url: 'https://github.com/suppers-ai/solobase'
  discord_url: 'https://discord.gg/jKqMcbrVzm'
  
menu:
  main:
    - name: 'Home'
      url: '/'
      weight: 10
    - name: 'Documentation'
      url: '/docs/'
      weight: 20
    - name: 'Live Demo'
      url: 'https://solobase-demo.fly.dev/'
      weight: 30
    - name: 'Discord'
      url: 'https://discord.gg/jKqMcbrVzm'
      weight: 40
    - name: 'GitHub'
      url: 'https://github.com/suppers-ai/solobase'
      weight: 50

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: github
    lineNos: false
  tableOfContents:
    startLevel: 2
    endLevel: 4
    ordered: false

# Build settings
build:
  writeStats: true
  
# Minification settings
minify:
  disableHTML: false
  disableCSS: false
  disableJS: true
  disableJSON: false
  disableSVG: false
  disableXML: false
  minifyOutput: false
  tdewolff:
    html:
      keepWhitespace: false
    css:
      keepCSS2: true
    js:
      keepVarNames: true
      noNullishOperator: true
  
# Asset processing
assets:
  disableCSS: false
  disableJS: false
  
# Image processing
imaging:
  resampleFilter: "CatmullRom"
  quality: 85
  anchor: "smart"
  
# Development server settings
server:
  headers:
    - for: "/**"
      values:
        X-Frame-Options: "DENY"
        X-XSS-Protection: "1; mode=block"
        X-Content-Type-Options: "nosniff"
        Referrer-Policy: "strict-origin-when-cross-origin"
        Content-Security-Policy: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com; connect-src 'self'"

# Output settings
outputs:
  home: ["HTML", "RSS"]
  page: ["HTML"]
  section: ["HTML", "RSS", "JSON"]